### ISSUE TITLE
Error:  identifier starts immediately after numeric literal

### ISSUE THREAD

**Issue by opensas** [SUPERCILEX/gnome-clipboard-history#41] opened 2022-03-02 05:25 UTC
### Describe the bug

After installing the extension thru https://extensions.gnome.org/extension/4839/clipboard-history/ I get the following error:

```
SyntaxError: identifier starts immediately after numeric literal

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

### How To Reproduce

navigate to https://extensions.gnome.org/extension/4839/clipboard-history/

click the ON/OFF toggle

#### Versions

```
$ gnome-shell --version; echo -n "GCH "; gnome-extensions show clipboard-history@alexsaveau.dev | grep Version; gsettings --schemadir ~/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/schemas list-recursively org.gnome.shell.extensions.clipboard-history
GNOME Shell 3.28.4
GCH gnome-extensions: command not found
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history preview-size 100
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history display-mode 0
```

#### Steps to repro

What causes the crash/bug?

### Additional context (if a crash, provide stack trace)

```shell
$ uname -a
Linux xps 5.4.0-86-generic #97~18.04.1-Ubuntu SMP Sat Sep 18 03:11:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
sas@xps ~ 
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by SUPERCILEX** [comment] 2022-03-02 05:29
Duplicate of https://github.com/SUPERCILEX/gnome-clipboard-history/issues/37

**Closed by SUPERCILEX** 2022-03-02 05:29 UTC
Labels: bug
